name: Keep Alive
on:
  schedule:
    - cron: '*/05 * * * *' # Every 15 minutes
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render
        run: curl -s -o /dev/null -w "%{http_code}" https://reminder-app-gap4.onrender.com